Update build.yml
awdawd

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,26 +43,34 @@ jobs:
         run: |
           pnpm run make  # 构建macOS版应用(包括ARM架构)
 
-      - name: Cleanup Artifacts for Windows
-        if: matrix.os == 'windows-latest'
+       # step5: cleanup artifacts in dist_electron
+      - name: cleanup artifacts for windows
+        if: matrix.os == 'windows-2019'
         run: |
-          mkdir dist
-          npx del-cli "dist/*" "!dist/*.exe" "!dist/*.zip" "!dist/*.yml"  # 清理Windows构建产物,只保留特定文件
-
-      - name: Cleanup Artifacts for MacOS
-        if: matrix.os == 'macos-latest'
+          mkdir artifacts
+          mv release/*.exe artifacts || true
+      - name: cleanup artifacts for macosZ
+        if: matrix.os == 'macos-10.15'
         run: |
-          mkdir dist
-          npx del-cli "dist/*" "!dist/(*.dmg|*.zip|latest*.yml)"  # 清理macOS构建产物,只保留特定文件
-
+          mkdir artifacts
+          mv release/*.dmg artifacts || true
+      - name: cleanup artifacts for Ubuntu
+        if: matrix.os == 'ubuntu-18.04'
+        run: |
+          mkdir artifacts
+          mv release/*.dmg artifacts || true
+      # step6: upload artifacts
       - name: upload artifacts
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v2
         with:
           name: ${{ matrix.os }}
-          path: dist # 上传构建产物作为工作流artifact
+          path: artifacts
 
+      # step7: create release
       - name: release
         uses: softprops/action-gh-release@v1
-        if: startsWith(github.ref, 'refs/tags/') # 只在推送标签时创建release
+        if: startsWith(github.ref, 'refs/tags/')
         with:
-          files: "dist/**" # 将dist目录下所有文件添加到release
+          files: 'artifacts/**'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
